image: python:3.12-slim

stages:
    - style
    - tests

style:
    stage: style
    before_script:
        - pip install flake8
    script:
        - flake8 --ignore F401 --max-line-length=100
    allow_failure: true

tests:
    stage: tests
    before_script:
        - pip install pytest
        - pip install numpy
        - pip install pandas
    script:
        - python -m pytest tests/
