image: python:3.7-stretch

stages:
    - style
    - tests

style:
    stage: style
    before_script:
        - pip install flake8
    script:
        - flake8 --ignore F401 --max-line-length=100
    allow_failure: true

tests:
    stage: tests
    script:
        - pytest
